baseurl = "http://peterspackman.science/"
title = "Peter R. Spackman -- Homepage"
author = "Peter R. Spackman"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"

pygmentsstyle       = "bw"
pygmentscodefences  = true
publishDir = "docs"

[params]
  sitename = "PRS"

[[menu.main]]
    name = "About"
    url  = "about"
[[menu.main]]
    name = "Projects"
    url  = "https://github.com/peterspackman"
[[menu.main]]
    name = "Resume"
    url  = "resume"

