baseurl = "http://peterspackman.science/"
title = "Peter R. Spackman"
author = "Peter R. Spackman"
languagecode = "en"
theme = "hemingway2"
copyright = "&copy; <a href=\"https://github.com/peterspackman\">Peter Spackman</a> 2018"

[taxonomies]
tag = "tags"
category = "categories"

[params]

[params.highlight]
style = "github"
languages = ["python", "javascript", "fortran", "c"]

[[params.social]]
url = "/about"
fa_icon = "fa-question-circle"

[[params.social]]
url = "https://github.com/peterspackman"
fa_icon = "fa-github"

[[params.social]]
url = "https://gitlab.com/Spackman"
fa_icon = "fa-gitlab"

[[params.social]]
url = "https://twitter.com/prspackman"
fa_icon = "fa-twitter"

[[params.social]]
url = "https://scholar.google.com.au/citations?user=GmSR9oIAAAAJ&hl=en"
fa_icon = "fa-graduation-cap"

[[params.social]]
url = "/index.xml"
